[package]
name = "knock100"
version = "0.1.0"
authors = ["nnsnico <y_toyama@fancs.com>"]
edition = "2018"

[[bench]]
name = "chapter_02"
harness = false

[dependencies]
rand = "0.7.0"

[dev-dependencies]
bencher = "0.1.5"

